language: c

before_script:
  - echo "deb http://archive.ubuntu.com/ubuntu/ quantal main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install valac-0.18 libglib2.0-dev gobject-introspection libgirepository1.0-dev

script:
  - ./waf configure --prefix=/usr
  - ./waf build
  - sudo ./waf install

notifications:
  email:
    recipients:
      - dsvensson@gmail.com
    on_success: change
    on_failure: always
